controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

firm:
    resource: ../../src/Controller/Firm
    type: annotation
    prefix: /firms
